version: '3.8'

networks:
  dev_springcloud:
    external: true

services:
  nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos
    restart: unless-stopped
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    volumes:
      - ./nacos/standalone-logs/:/home/nacos/logs
      - ./nacos/application.properties:/home/nacos/conf/application.properties
    # expose:
    #   - 8848
    #   - 9848
    ports:
      - "8848:8848"
      - "9848:9848"
    networks:
      - dev_springcloud
  
  seata-server:
    image: seataio/seata-server:${SEATA_SERVER_VERSION}
    container_name: seata
    restart: unless-stopped
    expose:
      - 8091
      - 7091
    environment:
      - SEATA_PORT=8091
      - STORE_MODE=file
    networks:
      - dev_springcloud