version: "3.8"

networks:
  monitoring:
    driver: bridge

services:
  nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    volumes:
      - ./nacos/standalone-logs/:/home/nacos/logs
      - ./nacos/application.properties:/home/nacos/confd/application.properties
    expose:
      - 8848
      - 9848
    networks:
      - monitoring
    labels:
      org.label-schema.group: "monitoring"
